apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/demo:latest
        ports:
        - containerPort: 3000
